CREATE TABLE jw_lectures (
    id bigint not null auto_increment,
    lecture_number integer not null,
    lecture_title varchar(255) not null,
    primary key (id)
) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

INSERT INTO jw_lectures (lecture_number, lecture_title)
VALUES
(1, 'Jak dobrze znasz Boga?'),
(2, 'Czy przeżyjesz dni ostatnie?'),
(3, 'Dotrzymuj kroku zjednoczonej organizacji Jehowy'),
(4, 'Otaczają nas dowody na istnienie Boga'),
(5, 'Prawdziwa pomoc dla rodzin'),
(6, 'Potop z czasów Noego - jakie znaczenie ma dla ciebie?'),
(7, 'Naśladujmy miłosierdzie Boga'),
(8, 'Żyjmy nie dla siebie, ale dla woli Bożej'),
(9, 'Bądź słuchaczem i wykonawcą Słowa Bożego'),
(10, 'Bądźmy uczciwi we wszystkim, co mówimy i robimy'),
(11, 'Naśladowcy Chrystusa ‘nie są częścią świata‘'),
(12, 'Twój stosunek do władzy ma znaczenie dla Boga'),
(13, 'Zbożny pogląd na seks i małżeństwo'),
(14, 'Czysty lud przysparza szacunku Jehowie'),
(15, 'Wyświadczajmy dobro wszystkim'),
(16, 'Umacniajmy swoją więź z Bogiem'),
(17, 'Wychwalajmy Boga wszystkim, co mamy'),
(18, 'Niech Jehowa będzie twoją twierdzą'),
(19, 'Skąd można się dowiedzieć, co przyniesie przyszłość?'),
(20, 'Czy nadeszła pora, żeby Bóg objął władzę nad światem?'),
(21, 'Doceniaj swoje miejsce w Królestwie Bożym'),
(22, 'Czy korzystasz z tego, co zapewnia ci Jehowa?'),
(23, 'Życie naprawdę ma sens'),
(24, 'Czy znalazłeś ‘niezwykle cenną perłę‘?'),
(25, 'Przeciwstawiaj się duchowi świata!'),
(26, 'Jak ważny jesteś dla Boga?'),
(27, 'Dobry początek małżeństwa'),
(28, 'Okazuj w małżeństwie szacunek i miłość'),
(29, 'Obowiązki i radości rodziców'),
(30, 'Jak ulepszyć komunikację w rodzinie'),
(31, 'Czy jesteś świadomy swoich potrzeb duchowych?'),
(32, 'Jak sobie radzić z problemami'),
(33, 'Czy kiedyś doczekamy się prawdziwej sprawiedliwości?'),
(35, 'Czy możesz i czy będziesz żyć wiecznie?'),
(36, 'Czy na tym życiu wszystko się kończy?'),
(37, 'Czy podążanie drogami Bożymi naprawdę przynosi korzyści?'),
(38, 'Jak przeżyć koniec świata?'),
(39, 'Bądź pewny zwycięstwa Boga!'),
(40, 'Co przyniesie najbliższa przyszłość?'),
(41, '‘Stójcie i patrzcie, jak Jehowa zapewnia wam wybawienie‘'),
(42, 'Co dla ciebie oznacza Królestwo Boże?'),
(43, 'Przestrzeganie Bożych wymagań zawsze wychodzi na dobre'),
(44, 'Jaką korzyść przynoszą nam nauki Jezusa?'),
(45, 'Podążaj drogą prowadzącą do życia'),
(46, 'Zachowuj silną wiarę do samego końca'),
(48, 'Jak zachowywać chrześcijańską lojalność w czasie prób'),
(49, 'Oczyszczona ziemia - czy to możliwe?'),
(50, 'Jak podejmować dobre decyzje'),
(51, 'Czy prawda zmienia twoje życie?'),
(52, 'Kto jest twoim Bogiem?'),
(53, 'Czy twój sposób myślenia jest zgodny z myślami Boga?'),
(54, 'Rozwijaj wiarę w Boga i Jego obietnice'),
(55, 'Jak możesz wyrobić sobie dobrą opinię u Boga?'),
(56, 'Któremu przywódcy możesz zaufać?'),
(57, 'Wytrwanie pośród prześladowań'),
(58, 'Kim są prawdziwi naśladowcy Chrystusa?'),
(59, 'Żąć będziesz to, co siejesz'),
(60, 'Co nadaje życiu sens?'),
(61, 'Czyim obietnicom ufasz?'),
(62, 'Jedyne lekarstwo dla chorej ludzkości'),
(63, 'Czy masz ducha ewangelizacji?'),
(64, 'Czy będziesz kochać przyjemności czy Boga?'),
(65, 'Jak pielęgnować pokój w świecie pełnym gniewu'),
(66, 'Czy weźmiesz udział w duchowych żniwach?'),
(67, 'Rozmyślaj nad Słowem Jehowy i Jego działaniami'),
(68, '‘Wspaniałomyślnie przebaczajcie sobie nawzajem‘'),
(69, 'Dlaczego okazywać ofiarną miłość?'),
(70, 'Pokładaj ufność w Jehowie'),
(71, 'Jak i dlaczego powinniśmy zachowywać czujność?'),
(72, 'Miłość znakiem rozpoznawczym prawdziwych chrześcijan'),
(73, 'Co robić, żeby ‘nasze serce stało się mądre‘?'),
(74, '‘Oczy Jehowy patrzą‘ na nas'),
(75, 'Popieraj władzę Jehowy'),
(76, 'Czy zasady biblijne mogą nam pomóc w rozwiązywaniu problemów?'),
(77, '‘Prześcigajcie się w okazywaniu gościnności‘'),
(78, 'Służ Jehowie radosnym sercem'),
(79, 'Z kim chcesz się przyjaźnić?'),
(80, 'Na czym opierasz swoją nadzieję - na nauce czy na Biblii?'),
(81, 'Kto może uczestniczyć w pozyskiwaniu uczniów Chrystusa?'),
(82, 'Czy Jehowa i Chrystus wchodzą w skład Trójcy?'),
(83, 'Czas sądu nad religią'),
(84, 'Czy unikniesz losu tego świata?'),
(85, 'Dobra nowina w świecie pełnym przemocy'),
(86, 'Modlitwy, których Bóg wysłuchuje'),
(87, 'Jaka więź łączy cię z Bogiem?'),
(88, 'Dlaczego warto trzymać się zasad biblijnych?'),
(89, 'Przyjdź, jeśli jesteś spragniony prawdy!'),
(90, 'Zabiegaj o rzeczywiste życie'),
(91, 'Obecność i panowanie Mesjasza'),
(92, 'Rola religii w dzisiejszym świecie'),
(93, 'Klęski żywiołowe - kiedy się skończą?'),
(94, 'Jak religia prawdziwa zaspokaja potrzeby społeczeństwa ludzkiego'),
(95, 'Biblijny pogląd na praktyki spirytystyczne'),
(96, 'Jaka przyszłość czeka religię?'),
(97, 'Pozostańmy nienaganni wśród spaczonego pokolenia'),
(98, '‘Zmienia się scena tego świata‘'),
(99, 'Dlaczego można zaufać Biblii'),
(100, 'Prawdziwa przyjaźń z Bogiem i bliźnimi'),
(101, 'Jehowa - Wspaniały Stwórca'),
(102, 'Zwracaj uwagę na słowo prorocze'),
(103, 'Jak znajdować radość w służeniu Bogu'),
(104, 'Rodzice, czy budujecie z materiałów ogniotrwałych?'),
(105, 'Gdzie szukać pocieszenia w naszych udrękach'),
(106, 'Bóg nie puści płazem rujnowania ziemi'),
(107, 'Jak zachować dobre sumienie w grzesznym świecie'),
(108, 'Jak wyzwolić się od strachu przed przyszłością'),
(109, 'Królestwo Boże jest bliskie'),
(110, 'Dawanie pierwszeństwa Bogu — gwarancją szczęścia w życiu rodzinnym'),
(111, 'W jaki sposób ludzkość zostanie całkowicie uzdrowiona?'),
(112, 'Jak okazywać miłość w świecie pełnym bezprawia'),
(113, 'Jak młodzi mogą osiągnąć sukces i szczęście?'),
(114, 'Podziwianie cudów stworzenia Bożego'),
(115, 'Jak się chronić przed sidłami Szatana'),
(116, 'Mądrze dobieraj sobie towarzystwo'),
(117, 'Jak zło zwyciężać dobrem'),
(118, 'Patrzmy na młodzież oczami Jehowy'),
(119, 'Dlaczego trzymanie się z dala od świata jest dla chrześcijan dobrodziejstwem'),
(120, 'Dlaczego już teraz trzeba się podporządkować panowaniu Bożemu'),
(121, 'Ogólnoświatowa społeczność braterska uratowana z zagłady'),
(122, 'Kto zaprowadzi powszechny pokój?'),
(123, 'Dlaczego chrześcijanie muszą być inni'),
(124, 'Podstawa wiary w Boskie autorstwo Biblii'),
(125, 'Dlaczego ludzkość potrzebuje okupu'),
(126, 'Kto może zostać wybawiony?'),
(127, 'Co się dzieje z człowiekiem po śmierci?'),
(128, 'Czy piekło to naprawdę miejsce ognistych mąk?'),
(129, 'Czy Biblia uczy o Trójcy?'),
(130, 'Ziemia pozostanie na zawsze'),
(131, 'Czy naprawdę istnieje Diabeł?'),
(132, 'Zmartwychwstanie -zwycięstwo nad śmiercią!'),
(133, 'Czy twój pogląd na pochodzenie człowieka ma jakieś znaczenie?'),
(134, 'Czy chrześcijanie powinni przestrzegać sabatu?'),
(135, 'Świętość życia i krwi'),
(136, 'Czy Bóg aprobuje oddawanie Mu czci za pomocą wizerunków?'),
(137, 'Czy cuda opisane w Biblii rzeczywiście się zdarzyły?'),
(138, 'Kierujmy się w zdeprawowanym świecie trzeźwością umysłu'),
(139, 'Mądrość Boża w świecie hołdującym nauce'),
(140, 'Kim naprawdę jest Jezus Chrystus?'),
(141, '`Całe stworzenie wzdycha` — kiedy to się skończy?'),
(142, 'Dlaczego szukać schronienia u Jehowy'),
(143, 'Zaufaj Bogu wszelkiej pociechy'),
(144, 'Lojalny zbór pod przewodnictwem Chrystusa'),
(145, 'Któż jest jak Jehowa, nasz Bóg?'),
(146, 'Korzystaj z wykształcenia ku chwale Jehowy'),
(147, 'Ufaj w zbawczą moc Jehowy'),
(148, 'Czy podzielasz Boży pogląd na życie?'),
(149, 'Czy chodzisz z Bogiem?'),
(150, 'Czy ten świat czeka zagłada?'),
(151, 'Jehowa jest dla swego ludu ‘bezpiecznym wzniesieniem‘'),
(152, 'Prawdziwy Armagedon - dlaczego? Kiedy?'),
(153, 'Stale pamiętaj o ‘budzącym lęk dniu Jehowy‘'),
(154, 'Rządy ludzkie na szalach wagi'),
(155, 'Czy nadeszła godzina sądu nad Babilonem?'),
(156, 'Czy Dzień Sądu powinien wzbudzać strach, czy nadzieję?'),
(157, 'Jak prawdziwi chrześcijanie zdobią naukę Bożą'),
(158, 'Bądź odważny i ufaj Jehowie'),
(159, 'Jak znaleźć bezpieczeństwo w niebezpiecznym świecie'),
(160, 'Zawsze pamiętaj, że jesteś chrześcijaninem!'),
(161, 'Dlaczego Jezus musiał cierpieć i umrzeć?'),
(162, 'Wyzwolenie ze świata pogrążonego w ciemności'),
(163, 'Dlaczego należy bać się prawdziwego Boga?'),
(164, 'Czy Bóg w dalszym ciągu sprawuje władzę nad światem?'),
(165, 'Jakie wartości sobie cenisz?'),
(166, 'Patrzmy w przyszłość z wiarą i odwagą'),
(167, 'Działaj mądrze w nierozumnym świecie'),
(168, 'Możesz cieszyć się poczuciem bezpieczeństwa w tym niespokojnym świecie!'),
(169, 'Dlaczego Biblia jest najlepszym przewodnikiem?'),
(170, 'Kto powinien sprawować władzę nad ludzkością?'),
(171, 'Możesz zaznawać pokoju — teraz i na zawsze!'),
(172, 'Jaką opinię wyrabiasz sobie u Boga?'),
(173, 'Czy istnieje religia, którą Bóg uznaje za prawdziwą?'),
(174, 'Kto będzie godny żyć w Bożym nowym świecie?'),
(175, 'Co przemawia za autentycznością Biblii?'),
(176, 'Kiedy nastanie prawdziwy pokój i bezpieczeństwo?'),
(177, 'Gdzie szukać pomocy w czasach udręki?'),
(178, 'Podążaj drogą nieskazitelności'),
(179, 'Odrzucaj świeckie rojenia, zabiegaj o realia Królestwa'),
(180, 'Dlaczego nadzieja zmartwychwstania powinna być dla nas czymś realnym'),
(181, 'Czy jest później, niż myślisz?'),
(182, 'Co już teraz czyni dla nas Królestwo Boże'),
(183, 'Odwracaj oczy od tego, co nic niewarte!'),
(184, 'Czy w chwili śmierci wszystko się kończy?'),
(185, 'Czy prawda wywiera wpływ na twoje życie?'),
(186, 'Przyłącz się do szczęśliwego ludu Bożego'),
(187, 'Dlaczego kochający Bóg dopuszcza zło?'),
(188, 'Czy pokładasz ufność w Jehowie?'),
(189, 'Chodzenie z Bogiem zapewnia wiecznotrwałe błogosławieństwa'),
(190, 'Obietnica doskonałego szczęścia rodzinnego'),
(191, 'W jaki sposób miłość i wiara zwyciężają świat'),
(192, 'Czy jesteś na drodze do życia wiecznego?'),
(193, 'Zbliża się wyzwolenie udręczonej ludzkości'),
(194, 'Jakie korzyści przynosi nam zbożna mądrość');